### ISSUE TITLE
iOS9 and 10 backward compatibility not working

### ISSUE THREAD

**Issue by marclefrancois** [samrayner/ColorAssetCatalog#10]
Hi, 

Just wanted to report that the backward compatibility feature was sadly broken by recent versions of xcode. The `*.xcassets` folder are now compiled into a single assets.car file that is not openable.

So the following code in `ColorAssetManager` does not work anymore:
```
func asset(named name: String) -> ColorAsset? {
        guard let dir = (bundle ?? Bundle.main).resourceURL?.appendingPathComponent("\(catalogName).xcassets"),
            let files = try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil, options: []),
            let colorset = files.first(where: { $0.lastPathComponent == "\(name).colorset" }),
            let data = try? Data(contentsOf: colorset.appendingPathComponent("Contents.json")),
            let catalog = try? JSONDecoder().decode(ColorAssetCatalog.self, from: data)
            else {
                return nil
        }
```
The problematic line is :
```
let files = try? FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil, options: [])
```
Because the folder does not exists

I tried to find  a way to extract the colors from the `.car` file without success.

**Comment by marclefrancois** [comment]
The error:
```
Error Domain=NSCocoaErrorDomain Code=260 "The folder “Colors.xcassets” doesn’t exist." UserInfo={NSFilePath=/Users/marclefrancois/Library/Developer/CoreSimulator/Devices/BDFA542F-5BC5-4579-870D-C070A90676EF/data/Containers/Bundle/Application/FEEE9D56-C777-479E-902B-22EFFEF25EBB/OptaniaPsyMobile.app/Colors.xcassets, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x600000248dc0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```
I do have a `Colors.xcassets` file in my xcode project

**Comment by samrayner** [comment]
Thanks @marclefrancois. Unfortunately, as I increased the minimum iOS version of my app to 11, I no longer need this. If you manage to fix it please feel free to do a PR but I don't have plans to maintain this repo anymore otherwise.

**Comment by marclefrancois** [comment]
Thanks for the update!

I simply switched to another solution since I suspect there isn't really a solution. Except someone coming up with a way to read the compiled assets.car
