### ISSUE TITLE
JSONDecoder doesn't decode the Contents.json file (returns nil)

### ISSUE THREAD

**Issue by fwaddle** [samrayner/ColorAssetCatalog#2]
I've got a set of colours in the file like this one:
```
{
  "info" : {
    "version" : 1,
    "author" : "xcode"
  },
  "colors" : [
    {
      "idiom" : "universal",
      "color" : {
        "color-space" : "srgb",
        "components" : {
          "red" : "1.000",
          "alpha" : "1.000",
          "blue" : "1.000",
          "green" : "1.000"
        }
      }
    }
  ]
}
```

When tracing through the method I can see that all is going well until it tries to JSON decode the file.
Are you able to see anything wrong with the above file that would give a reason as to why it's not working?

When I catch the JSONDecode error, this is what it shows:

typeMismatch(Swift.Double, Swift.DecodingError.Context(codingPath: [ColorAssetCatalog.ColorAssetCatalog.(CodingKeys in _DAE07DEB4F1D47BCAEDAF908209E6C48).colors, Foundation.(_JSONKey in _12768CA107A31EF2DCE034FD75B541C9)(stringValue: "Index 0", intValue: Optional(0)), ColorAssetCatalog.ColorAsset.(CodingKeys in _DAE07DEB4F1D47BCAEDAF908209E6C48).color, ColorAssetCatalog.ColorAsset.Color.(CodingKeys in _DAE07DEB4F1D47BCAEDAF908209E6C48).components, ColorAssetCatalog.ColorAsset.Color.Components.(CodingKeys in _DAE07DEB4F1D47BCAEDAF908209E6C48).alpha], debugDescription: "Expected to decode Double but found a string/data instead.", underlyingError: nil))

**Comment by fwaddle** [comment]
I modified the code to get it to work but it doesn't matter as I still can't use the colour asset stuff with old versions of ios. It works fine if you do it in code but not if you use storyboards to set the colours. Bugger!

Thanks anyway.

**Comment by samrayner** [comment]
Odd, I wouldn't expect those component values to be Strings! They should always be numerical (without quotes) in the JSON. Did you modify or generate that JSON manually?

**Comment by adamwidera1978** [comment]
To reproduce, use the latest version of the Xcode. It saves the values of the colours as strings instead of doubles.

The decoding failure relates to this issue inside swift:
https://bugs.swift.org/browse/SR-5249

Modification to the ColorAssetCatalog.swift that would make it usable again is:

extension ColorAsset.Color {
    
    struct Components: Decodable {
        var alpha: CGFloat = 1
        var red: CGFloat = 0
        var green: CGFloat = 0
        var blue: CGFloat = 0

        var white: CGFloat? {
            didSet {
                guard let white = white else { return }
                red = white
                green = white
                blue = white
            }
        }
        
        enum CodingKeys: String, CodingKey {
            case alpha
            case red
            case green
            case blue
        }
        
        init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: CodingKeys.self)
            alpha = CGFloat(Double(try values.decode(String.self, forKey: .alpha))!)
            red = CGFloat(Double(try values.decode(String.self, forKey: .red))!)
            green = CGFloat(Double(try values.decode(String.self, forKey: .green))!)
            blue = CGFloat(Double(try values.decode(String.self, forKey: .blue))!)
        }
    }
}

**Comment by samrayner** [comment]
Thank you @adamwidera1978!

I've made the change. Will publish a new version to Cocoapods when I get a chance later.

https://github.com/samrayner/ColorAssetCatalog/commit/2b8a06c2178a75891e62586256d30dc7536077b6
