### ISSUE TITLE
Can't use with NSAttributedString in iOS 10

### ISSUE THREAD

**Issue by VMavrin** [samrayner/ColorAssetCatalog#3]
Impossible using colors as attributes in attributed strings with UILabel (iOS 10).

Example:
`UINavigationBar.appearance().titleTextAttributes = [NSForegroundColorAttributeName: UIColor(asset: "baseColor")]
`
Got error:
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UILabel: the use of CGColor for color properties or inside attributed strings is not supported.'

**Comment by samrayner** [comment]
`UIColor(asset: "baseColor")` does not return a CGColor, it returns a UIColor. I've updated the sample project with a test using NSAttributedString and it works fine. I would guess that this bug is caused by trying to set `titleTextAttributes` through UIAppearance?
